import * as _ from "./underscore";

const wordList = { // is called in translator
    " ": " ", // important
    ".": ".", // idek if this does anything
    "one": "e", // english first then gingerise
    "two": "iut",
    "three": "ert",
    "four": "poq",
    "five": "mak",
    "six": "kal",
    "seven": "dagnek",
    "eight": "renom",
    "nine": "gert",
    "ten": "tekk",
    "eleven": "tekk-e",
    "twelve": "tekk-iut",
    "thirteen": "tekk-ert",
    "fourteen": "tekk-poq",
    "fifteen": "tekk-mak",
    "sixteen": "tekk-kal",
    "seventeen": "dagnek",
    "eighteen" : "tekk-renom",
    "nineteen": "tekk-gert",
    "twenty": "iuttek",
    "thirty": "erttek",
    // ### COLOURS ###
    "red": "gnig",
    "blue": "lubk",
    "green": "guyig",
    "yellow": "yumnlow",
    "white": "wirlsk",
    "black": "bukle",
    "pink": "perik",
    "purple": "porkprle",
    "orange": "gingupor",
    // ### ACUTAL REAL WORDS
    "difficult": "difrict",
    "rusty": "tyrix",
    "gay": "hcama",
    "hey": "re",
    "hi": "re",
    "hello":"reeq",
    "what": "vau",
    "are": "trl",
    "you": "uio",
    "your": "uoir",
    "it": "ut",
    "do": "od",
    "wagwan": "ezvsan",
    "yo": "som",
    "greetings": "retqion",
    "goodbye": "betqion",
    "goodnight": "beeqhigt",
    "night": "higt",
    "see": "fre",
    "later": "jetour",
    "fuck": "wers",
    "fucking": "wersen",
    "i": "ymi",
    "understand": "upordestn",
    "me": "mi",
    "my": "mi",
    "off": "tes",
    "how": "heriw",
    "good": "vig",
    "bad": "giv",
    "okay": "piop",
    "up": "pu",
    "to": "ort",
    "has": "gus",
    "no": "noj",
    "dad": "dosn",
    "yes": "yert",
    "this": "dus",
    "nigga": "nokneg",
    "got": "ugop",
    "shot": "powt"



};

const gingList = _.invert(wordList); // to be called when translating from gingerese into english